### ISSUE TITLE
what would i put in a procfile like worker: python ?

### ISSUE THREAD

**Issue by GreatZardasht** [pawbot-discord/Pawbot#13]
if i were to host a bot with this code on heroku free hoster ill need a proc file whic basically runs a file that is the main bot code that runs every other code with it like eg worker: python pawbot.py  but i cant see whic file to run ????

**Comment by lyricalpaws** [comment]
I only provide support for hosting on a vps (virtual private server), it was never intended to be hosted on Heroku. Especially with the database hooks that it depends on. Sorry if this isn't what you wanted. 

p.s. Heroku's free plan isn't stable enough to run a discord bot, use a vps like Linode for about $5 a month.
